# Generated by ChatGPT
# Task:
# - Take PNG files from:
#   ../drafts/assets/img/map/{map2p|map3p|map4p|map5p}/areas/*.png
# - Detect area enclosed by white contour
# - Fill interior with 50% transparent white
# - Save results to:
#   ./img/map/{map2p|map3p|map4p|map5p}/areas/

try:
    import os
    from PIL import Image, ImageDraw

    MAP_NAMES = ["map2p", "map3p", "map4p", "map5p"]

    def fill_inside_white_contour(input_path: str, output_path: str) -> dict:
        """
        Finds the region enclosed by a white contour and overlays it
        with semi-transparent white.
        """
        img = Image.open(input_path).convert("RGBA")
        w, h = img.size

        r, g, b, a = img.split()
        r_b = r.tobytes()
        g_b = g.tobytes()
        b_b = b.tobytes()
        a_b = a.tobytes()

        contour_free = Image.new("L", (w, h), 255)
        cf = contour_free.load()

        WHITE_T = 240
        ALPHA_T = 1

        idx = 0
        for y in range(h):
            for x in range(w):
                rr = r_b[idx]
                gg = g_b[idx]
                bb = b_b[idx]
                aa = a_b[idx]
                idx += 1

                is_contour = (
                    aa >= ALPHA_T and
                    rr >= WHITE_T and
                    gg >= WHITE_T and
                    bb >= WHITE_T
                )

                cf[x, y] = 0 if is_contour else 255

        # Find a free border pixel to start flood fill (outside area)
        start = None
        for x in range(w):
            if cf[x, 0] == 255:
                start = (x, 0)
                break
            if cf[x, h - 1] == 255:
                start = (x, h - 1)
                break

        if start is None:
            for y in range(h):
                if cf[0, y] == 255:
                    start = (0, y)
                    break
                if cf[w - 1, y] == 255:
                    start = (w - 1, y)
                    break

        if start is None:
            return {"ok": False, "reason": "No free border pixel found"}

        ImageDraw.floodfill(contour_free, start, value=0, thresh=0)

        interior_pixels = contour_free.histogram()[255]
        if interior_pixels == 0:
            return {"ok": False, "reason": "No enclosed interior detected"}

        overlay_alpha = contour_free.point(lambda v: 128 if v == 255 else 0)
        overlay_rgb = Image.new("RGB", (w, h), (255, 255, 255))
        overlay = Image.merge("RGBA", (*overlay_rgb.split(), overlay_alpha))

        result = Image.alpha_composite(img, overlay)

        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        result.save(output_path)

        return {"ok": True, "interior_pixels": interior_pixels}

    def main():
        script_dir = os.path.dirname(os.path.abspath(__file__))

        src_root = os.path.normpath(
            os.path.join(script_dir, "..", "drafts", "assets", "img", "map")
        )
        dst_root = os.path.join(script_dir, "img", "map")

        total = 0

        for map_name in MAP_NAMES:
            src_dir = os.path.join(src_root, map_name, "areas")
            dst_dir = os.path.join(dst_root, map_name, "areas")

            if not os.path.isdir(src_dir):
                print(f"Source folder not found: {src_dir}")
                continue

            png_files = [
                f for f in os.listdir(src_dir)
                if f.lower().endswith(".png")
            ]

            if not png_files:
                print(f"No PNG files in {src_dir}")
                continue

            print(f"Processing {map_name}: {len(png_files)} file(s)")

            for name in png_files:
                in_path = os.path.join(src_dir, name)
                out_path = os.path.join(dst_dir, name)

                try:
                    info = fill_inside_white_contour(in_path, out_path)
                    if info.get("ok"):
                        total += 1
                        print(f"  OK: {name}")
                    else:
                        print(f"  SKIP: {name} ({info.get('reason')})")
                except Exception as e:
                    print(f"  ERROR: {name}: {e}")

        print(f"Done. Generated {total} file(s).")

    if __name__ == "__main__":
        main()

except Exception as e:
    print("Fatal error:", e)

finally:
    # Keep console window open when started from Explorer
    try:
        input("Press Enter to exit...")
    except Exception:
        pass
